spring:
  docker:
    compose:
      enabled: true
      file: ../compose.yaml
      lifecycle-management: start-only

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.ceudelavanda.lavandaflow: DEBUG
    org.hibernate.SQL: DEBUG