spring:
  application:
    name: lavanda-flow

  jpa:
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: when-authorized

lavanda:
  inventory:
    alerts:
      expiration-window-days: ${EXPIRATION_ALERT_WINDOW_DAYS:30}
