package com.ceudelavanda.lavandaflow.inventory.application.initialsnapshot;

/** Stable, source-specific validation codes for rejected snapshot rows. */
public enum InitialInventoryImportValidationCode {
    MALFORMED_ROW,
    BLANK_NAME,
    INVALID_REFERENCE,
    INVALID_GENDER,
    INVALID_QUANTITY,
    INVALID_WITHDRAWAL_ADJUSTMENT,
    NEGATIVE_ADJUSTED_QUANTITY,
    INVALID_EXPIRATION,
    EXPIRATION_REQUIRED,
    EXPIRATION_BEFORE_EFFECTIVE_DATE,
    INVALID_ESSENCE_REFERENCE,
    INVALID_PRODUCTION_TYPE_CODE,
    LOT_CODE_REQUIRED,
    INVALID_LOT_CODE,
    DUPLICATE_LOT_CODE,
    CONFLICTING_PRODUCT_METADATA,
    CONFLICTING_FRAGRANCE_GENDER,
    DUPLICATE_NAME
}
